require "coffe.plugins"
require "coffe.options"
require "coffe.keymaps"
require "coffe.colorscheme"
require "coffe.cmp"
require "coffe.lsp"
require "coffe.telescope"
require "coffe.nvim-lastplace"
require "coffe.treesitter"
require "coffe.nvim-tree"
require "coffe.live-server"
require "coffe.trouble"
require "coffe.ft"

