alias nv="nvim"

alias gst="git status"
alias gc="git commit"
alias gco="git checkout"
alias gl="git pull"
alias gpom="git pull origin master"
alias gp="git push"
alias gd="git diff | mate"
alias gb="git branch"
alias gba="git branch -a"
alias del="git branch -d"
